###

GET http://localhost:3000/api/users

###

GET http://localhost:3000/api/users/id/:userId

###

GET http://localhost:3000/api/users/age/40

###

GET http://localhost:3000

###

POST http://localhost:3000/api/users/new
Content-Type: application/json

{
  "name": "Jill",
  "town": "Taurage",
  "age": 33
}